import { apiFetch } from "./client";
import type { Workspace, Doc, Project, Profile, Skill, Education, Certificate, Resume, ResumeItem, Portfolio, ChatResponse } from "./types";
export const api = {
  me: () => apiFetch<{id:string;email:string}>("/api/v1/me"),
  workspaces: () => apiFetch<Workspace[]>("/api/v1/workspaces"),
  createWorkspace: (b: {name:string;description?:string}) => apiFetch<Workspace>("/api/v1/workspaces",{method:"POST",body:JSON.stringify(b)}),
  workspace: (id:string) => apiFetch<Workspace>(`/api/v1/workspaces/${id}`),
  updateWorkspace: (id:string,b:Record<string,unknown>) => apiFetch<Workspace>(`/api/v1/workspaces/${id}`,{method:"PATCH",body:JSON.stringify(b)}),
  deleteWorkspace: (id:string) => apiFetch(`/api/v1/workspaces/${id}`,{method:"DELETE"}),
  wsDocuments: (wid:string) => apiFetch<Doc[]>(`/api/v1/workspaces/${wid}/documents`),
  uploadDocument: async (wid:string, file: File) => { const { supabase } = await import("../supabase"); const { data } = await supabase.auth.getSession(); const fd = new FormData(); fd.append("file", file); const { env } = await import("../env"); const r = await fetch(`${env.apiBase}/api/v1/workspaces/${wid}/documents`,{method:"POST",headers:{Authorization:`Bearer ${data.session?.access_token||""}`},body:fd}); if(!r.ok) throw new Error("Upload failed"); return r.json() as Promise<Doc>; },
  docDownload: (wid:string,did:string) => apiFetch<{url?:string;download_url?:string}>(`/api/v1/workspaces/${wid}/documents/${did}/download`),
  docIndex: (wid:string,did:string) => apiFetch(`/api/v1/workspaces/${wid}/documents/${did}/index`,{method:"POST"}),
  chat: (wid:string,b:Record<string,unknown>) => apiFetch<ChatResponse>(`/api/v1/workspaces/${wid}/chat`,{method:"POST",body:JSON.stringify(b)}),
  conversations: (wid:string) => apiFetch<{id:string;title?:string;created_at?:string}[]>(`/api/v1/workspaces/${wid}/conversations`),
  convMessages: (wid:string,cid:string) => apiFetch<{id:string;role?:string;content?:string;created_at?:string}[]>(`/api/v1/workspaces/${wid}/conversations/${cid}/messages`),
  deleteConversation: (wid:string,cid:string) => apiFetch(`/api/v1/workspaces/${wid}/conversations/${cid}`,{method:"DELETE"}),
  research: (wid:string,tool:string,b:Record<string,unknown>) => apiFetch(`/api/v1/workspaces/${wid}/research/${tool}`,{method:"POST",body:JSON.stringify(b)}),
  createProjectFromResearch: (wid:string,b:Record<string,unknown>) => apiFetch(`/api/v1/workspaces/${wid}/research/create-project`,{method:"POST",body:JSON.stringify(b)}),
  documents: (q="") => apiFetch<Doc[]>(`/api/v1/documents${q}`),
  projects: () => apiFetch<Project[]>("/api/v1/projects"),
  project: (id:string) => apiFetch<Project>(`/api/v1/projects/${id}`),
  createProject: (b:Record<string,unknown>) => apiFetch<Project>("/api/v1/projects",{method:"POST",body:JSON.stringify(b)}),
  updateProject: (id:string,b:Record<string,unknown>) => apiFetch<Project>(`/api/v1/projects/${id}`,{method:"PATCH",body:JSON.stringify(b)}),
  deleteProject: (id:string) => apiFetch(`/api/v1/projects/${id}`,{method:"DELETE"}),
  profile: () => apiFetch<Profile>("/api/v1/profile"),
  updateProfile: (b:Record<string,unknown>) => apiFetch<Profile>("/api/v1/profile",{method:"PATCH",body:JSON.stringify(b)}),
  skills: () => apiFetch<Skill[]>("/api/v1/career/skills"),
  createSkill: (b:Record<string,unknown>) => apiFetch<Skill>("/api/v1/career/skills",{method:"POST",body:JSON.stringify(b)}),
  deleteSkill: (id:string) => apiFetch(`/api/v1/career/skills/${id}`,{method:"DELETE"}),
  education: () => apiFetch<Education[]>("/api/v1/career/education"),
  createEducation: (b:Record<string,unknown>) => apiFetch<Education>("/api/v1/career/education",{method:"POST",body:JSON.stringify(b)}),
  deleteEducation: (id:string) => apiFetch(`/api/v1/career/education/${id}`,{method:"DELETE"}),
  certificates: () => apiFetch<Certificate[]>("/api/v1/career/certificates"),
  createCertificate: (b:Record<string,unknown>) => apiFetch<Certificate>("/api/v1/career/certificates",{method:"POST",body:JSON.stringify(b)}),
  deleteCertificate: (id:string) => apiFetch(`/api/v1/career/certificates/${id}`,{method:"DELETE"}),
  resumes: () => apiFetch<Resume[]>("/api/v1/resumes"),
  resume: (id:string) => apiFetch<Resume>(`/api/v1/resumes/${id}`),
  createResume: (b:Record<string,unknown>) => apiFetch<Resume>("/api/v1/resumes",{method:"POST",body:JSON.stringify(b)}),
  resumeItems: (rid:string) => apiFetch<ResumeItem[]>(`/api/v1/resumes/${rid}/items`),
  addResumeItem: (rid:string,b:Record<string,unknown>) => apiFetch<ResumeItem>(`/api/v1/resumes/${rid}/items`,{method:"POST",body:JSON.stringify(b)}),
  reorderResumeItems: (rid:string,items:{id:string;sort_order:number}[]) => apiFetch<ResumeItem[]>(`/api/v1/resumes/${rid}/items/reorder`,{method:"PATCH",body:JSON.stringify({items})}),
  deleteResumeItem: (rid:string,iid:string) => apiFetch(`/api/v1/resumes/${rid}/items/${iid}`,{method:"DELETE"}),
  portfolios: () => apiFetch<Portfolio[]>("/api/v1/portfolios"),
  portfolio: (id:string) => apiFetch<Portfolio>(`/api/v1/portfolios/${id}`),
  createPortfolio: (b:Record<string,unknown>) => apiFetch<Portfolio>("/api/v1/portfolios",{method:"POST",body:JSON.stringify(b)}),
  updatePortfolio: (id:string,b:Record<string,unknown>) => apiFetch<Portfolio>(`/api/v1/portfolios/${id}`,{method:"PATCH",body:JSON.stringify(b)}),
  pfProjects: (pid:string) => apiFetch<{id:string;project_id?:string}[]>(`/api/v1/portfolios/${pid}/projects`),
  pfAddProject: (pid:string,b:Record<string,unknown>) => apiFetch(`/api/v1/portfolios/${pid}/projects`,{method:"POST",body:JSON.stringify(b)}),
  pfSkills: (pid:string) => apiFetch<{id:string;skill_id?:string}[]>(`/api/v1/portfolios/${pid}/skills`),
  pfAddSkill: (pid:string,b:Record<string,unknown>) => apiFetch(`/api/v1/portfolios/${pid}/skills`,{method:"POST",body:JSON.stringify(b)}),
  pfEducation: (pid:string) => apiFetch<{id:string;education_id?:string}[]>(`/api/v1/portfolios/${pid}/education`),
  pfAddEducation: (pid:string,b:Record<string,unknown>) => apiFetch(`/api/v1/portfolios/${pid}/education`,{method:"POST",body:JSON.stringify(b)}),
  pfCertificates: (pid:string) => apiFetch<{id:string;certificate_id?:string}[]>(`/api/v1/portfolios/${pid}/certificates`),
  pfAddCertificate: (pid:string,b:Record<string,unknown>) => apiFetch(`/api/v1/portfolios/${pid}/certificates`,{method:"POST",body:JSON.stringify(b)}),
  publicPortfolio: (slug:string) => apiFetch<Record<string,unknown>>(`/api/v1/public/portfolios/${slug}`,{auth:false}),
  careerAi: (tool:string,b:Record<string,unknown>={}) => apiFetch(`/api/v1/career/ai/${tool}`,{method:"POST",body:JSON.stringify(b)}),
  careerConversations: () => apiFetch<{id:string;title?:string;created_at?:string}[]>("/api/v1/career/ai/conversations"),
  careerConversation: (id:string) => apiFetch<Record<string,unknown>>(`/api/v1/career/ai/conversations/${id}`),
  deleteCareerConversation: (id:string) => apiFetch(`/api/v1/career/ai/conversations/${id}`,{method:"DELETE"}),
  contact: (b:Record<string,unknown>) => apiFetch("/api/v1/contact",{method:"POST",body:JSON.stringify(b),auth:false}),
  adminMessages: () => apiFetch<{id:string;name?:string;email?:string;subject?:string;message?:string;status?:string;created_at?:string}[]>("/api/v1/contact/messages"),
  adminUpdateMessage: (id:string,b:Record<string,unknown>) => apiFetch(`/api/v1/contact/messages/${id}`,{method:"PATCH",body:JSON.stringify(b)}),
};
