"use client"; import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query"; import { api } from "@/lib/api/services"; import { LoadingState, EmptyState, ErrorState } from "@/components/PageStates"; import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Badge } from "@/components/ui/badge"; import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"; import { formatDate } from "@/lib/utils"; import Link from "next/link"; import { useState } from "react";
export default function Workspaces(){const qc=useQueryClient();const q=useQuery({queryKey:["workspaces"],queryFn:api.workspaces});const [name,setName]=useState("");const [desc,setDesc]=useState("");const [search,setSearch]=useState("");
 const create=useMutation({mutationFn:()=>api.createWorkspace({name,description:desc}),onSuccess:()=>{qc.invalidateQueries({queryKey:["workspaces"]});setName("");setDesc("");}});
 if(q.isLoading) return <LoadingState/>; if(q.error) return <ErrorState message="Failed to load workspaces" onRetry={()=>q.refetch()}/>;
 const list=(q.data||[]).filter(x=>x.name.toLowerCase().includes(search.toLowerCase()));
 return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-display text-2xl font-semibold tracking-tight">Research workspaces</h1><p className="mt-1 text-sm text-zinc-500">Organize documents and grounded AI around a topic.</p></div></div>
 <form onSubmit={e=>{e.preventDefault();create.mutate();}} className="mt-6 grid gap-3 rounded-2xl border border-zinc-900/[0.08] bg-white p-4 shadow-sm sm:grid-cols-[1fr_1fr_auto]"><div className="space-y-1"><Label htmlFor="wn">Workspace name</Label><Input id="wn" value={name} onChange={e=>setName(e.target.value)} required placeholder="e.g. Thesis literature"/></div><div className="space-y-1"><Label htmlFor="wd">Description</Label><Input id="wd" value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Optional"/></div><Button type="submit" disabled={create.isPending} className="self-end">{create.isPending?"Creating…":"Create"}</Button></form>
 <Input className="mt-5 max-w-sm" placeholder="Search workspaces…" value={search} onChange={e=>setSearch(e.target.value)} aria-label="Search workspaces"/>
 <div className="mt-5">{!list.length?<EmptyState title="No workspaces found" desc="Create your first workspace above."/>:<ul className="divide-y divide-zinc-900/[0.06] rounded-lg border border-zinc-900/[0.08] bg-white">{list.map(x=><li key={x.id} className="flex items-center justify-between px-5 py-4"><div><Link href={`/app/workspaces/${x.id}`} className="font-medium hover:underline">{x.name}</Link>{x.description&&<p className="mt-0.5 text-sm text-zinc-500">{x.description}</p>}</div><span className="text-xs text-zinc-500">{formatDate(x.created_at)}</span></li>)}</ul>}</div></div>;}
