"use client"; import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query"; import { api } from "@/lib/api/services"; import { LoadingState, EmptyState, ErrorState } from "@/components/PageStates"; import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Textarea } from "@/components/ui/textarea"; import { Label } from "@/components/ui/label"; import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"; import Link from "next/link"; import { useState } from "react";
export default function PortfolioPage(){const qc=useQueryClient();const q=useQuery({queryKey:["portfolios"],queryFn:api.portfolios});const [title,setTitle]=useState("");const [slug,setSlug]=useState("");const [sel,setSel]=useState("");
 const proj=useQuery({queryKey:["projects"],queryFn:api.projects});const skills=useQuery({queryKey:["skills"],queryFn:api.skills});
 const create=useMutation({mutationFn:()=>api.createPortfolio({title,slug}),onSuccess:()=>{qc.invalidateQueries({queryKey:["portfolios"]});setTitle("");setSlug("");}});
 if(q.isLoading) return <LoadingState/>;
 return <div><h1 className="text-2xl font-semibold tracking-tight">Portfolio Builder</h1><p className="mt-1 text-sm text-zinc-400">Curate real work into a public page recruiters can open.</p>
 <form onSubmit={e=>{e.preventDefault();create.mutate();}} className="mt-6 grid max-w-xl gap-2 sm:grid-cols-2"><Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Portfolio title" required aria-label="Title"/><Input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="slug (e.g. huss)" required aria-label="Slug"/><Button type="submit">Create portfolio</Button></form>
 {!q.data?.length?<div className="mt-5"><EmptyState title="No portfolios yet" desc="Create one and attach projects from your Career Hub data."/></div>:<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{q.data.map(p=><div key={p.id} className="rounded-lg border border-white/[0.08] bg-[#0F1511] p-4"><p className="font-medium">{p.title}</p><p className="mt-1 text-xs text-zinc-500">/p/{p.slug}</p><div className="mt-3 flex gap-2"><Button size="sm" variant="outline" onClick={()=>setSel(p.id)}>Manage</Button>{p.slug&&<Link href={`/p/${p.slug}`} target="_blank"><Button size="sm">View public</Button></Link>}</div></div>)}</div>}
 {sel&&<Card className="mt-6"><CardHeader><CardTitle>Attach to portfolio</CardTitle></CardHeader><CardContent><p className="text-sm text-zinc-400">Projects</p><div className="mt-2 flex flex-wrap gap-2">{(proj.data||[]).map(p=><Button key={p.id} size="sm" variant="outline" onClick={async()=>{await api.pfAddProject(sel,{project_id:p.id});alert("Project attached");}}>{String(p.title||p.name)}</Button>)}</div><p className="mt-5 text-sm text-zinc-400">Skills</p><div className="mt-2 flex flex-wrap gap-2">{(skills.data||[]).map(s=><Button key={s.id} size="sm" variant="outline" onClick={async()=>{await api.pfAddSkill(sel,{skill_id:s.id});alert("Skill attached");}}>{s.name}</Button>)}</div></CardContent></Card>}</div>;}
