"use client"; import { useAuth } from "@/components/AuthProvider"; import { supabase } from "@/lib/supabase"; import { useQuery } from "@tanstack/react-query"; import { api } from "@/lib/api/services"; import { LoadingState } from "@/components/PageStates"; import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Textarea } from "@/components/ui/textarea"; import { Label } from "@/components/ui/label"; import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"; import { useState, useEffect } from "react"; import { useRouter } from "next/navigation";
export default function Settings(){const {user}=useAuth();const router=useRouter();const prof=useQuery({queryKey:["profile"],queryFn:api.profile});const [full,setFull]=useState("");const [headline,setHeadline]=useState("");const [bio,setBio]=useState("");const [pw,setPw]=useState("");const [msg,setMsg]=useState("");
 useEffect(()=>{if(prof.data){setFull(String(prof.data.full_name||""));setHeadline(String(prof.data.headline||""));setBio(String(prof.data.bio||""));}},[prof.data]);
 if(!user) return <LoadingState/>;
 async function saveProfile(e:React.FormEvent){e.preventDefault();await api.updateProfile({full_name:full,headline,bio});setMsg("Profile saved.");}
 async function changePw(e:React.FormEvent){e.preventDefault();const {error}=await supabase.auth.updateUser({password:pw});setMsg(error?error.message:"Password updated.");}
 return <div className="max-w-2xl"><h1 className="font-display text-2xl font-semibold tracking-tight">Settings</h1><p className="mt-1 text-sm text-zinc-500">{user.email} · User ID: {user.id}</p>
 <Card className="mt-6"><CardHeader><CardTitle>Profile</CardTitle></CardHeader><CardContent><form onSubmit={saveProfile} className="space-y-4"><div className="space-y-2"><Label htmlFor="fn">Full name</Label><Input id="fn" value={full} onChange={e=>setFull(e.target.value)}/></div><div className="space-y-2"><Label htmlFor="hl">Headline</Label><Input id="hl" value={headline} onChange={e=>setHeadline(e.target.value)}/></div><div className="space-y-2"><Label htmlFor="bio">Bio</Label><Textarea id="bio" value={bio} onChange={e=>setBio(e.target.value)} rows={4}/></div><Button type="submit">Save profile</Button></form></CardContent></Card>
 <Card className="mt-6"><CardHeader><CardTitle>Password</CardTitle></CardHeader><CardContent><form onSubmit={changePw} className="space-y-4"><div className="space-y-2"><Label htmlFor="np">New password</Label><Input id="np" type="password" value={pw} onChange={e=>setPw(e.target.value)} required/></div><Button type="submit" variant="outline">Update password</Button></form>{msg&&<p className="mt-3 text-sm text-emerald-700" role="status">{msg}</p>}</CardContent></Card>
 <Button variant="outline" className="mt-6" onClick={async()=>{await supabase.auth.signOut();router.replace("/login");}}>Sign out</Button></div>;}
