"use client"; import { useState } from "react"; import { MarketingHeader, MarketingFooter } from "@/components/Marketing"; import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Textarea } from "@/components/ui/textarea"; import { Label } from "@/components/ui/label"; import { api } from "@/lib/api/services";
export default function Contact(){const [f,setF]=useState({name:"",email:"",subject:"Support",message:""});const [st,setSt]=useState<"idle"|"loading"|"ok"|"err">("idle");const [msg,setMsg]=useState("");
 async function onSubmit(e:React.FormEvent){e.preventDefault(); if(!f.name||!f.email||!f.message){setSt("err");setMsg("Please fill name, email and message.");return;} if(f.message.length>1500){setSt("err");setMsg("Message too long (max 1500 characters).");return;} setSt("loading"); try{await api.contact({name:f.name,email:f.email,subject:f.subject,message:f.message}); setSt("ok"); setMsg("Message sent. We will reply by email."); setF({name:"",email:"",subject:"Support",message:""});}catch(err){setSt("err"); setMsg(err instanceof Error?err.message:"Failed to send. Try again.");}}
 return <div className="bg-[#050807] text-zinc-100"><MarketingHeader/><main className="mx-auto max-w-3xl px-4 py-16 sm:px-6"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-indigo-300">Contact</p><h1 className="font-display mt-4 text-4xl font-semibold tracking-tight">Talk to us.</h1><p className="mt-3 text-zinc-400">Support, feedback, partnership or a bug — online product, email replies. No office address; ZEVQYN is fully online.</p><form onSubmit={onSubmit} className="mt-8 space-y-4 rounded-lg border border-white/[0.08] bg-[#0F1511] p-6">
 <div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="name">Name</Label><Input id="name" value={f.name} onChange={e=>setF({...f,name:e.target.value})} required/></div><div className="space-y-2"><Label htmlFor="email">Email</Label><Input id="email" type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})} required/></div></div>
 <div className="space-y-2"><Label htmlFor="subject">Subject</Label><select id="subject" value={f.subject} onChange={e=>setF({...f,subject:e.target.value})} className="flex h-9 w-full rounded-md border border-white/10 bg-zinc-900 px-3 text-sm"><option>Support</option><option>Feedback</option><option>Partnership</option><option>Bug</option><option>Other</option></select></div>
 <div className="space-y-2"><Label htmlFor="message">Message ({f.message.length}/1500)</Label><Textarea id="message" rows={6} maxLength={1500} value={f.message} onChange={e=>setF({...f,message:e.target.value})} required/></div>
 {msg&&<p role="status" className={st==="ok"?"text-sm text-emerald-300":"text-sm text-red-300"}>{msg}</p>}
 <Button type="submit" disabled={st==="loading"}>{st==="loading"?"Sending…":"Send message"}</Button></form></main><MarketingFooter/></div>;}
