"use client"; import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query"; import { api } from "@/lib/api/services"; import { LoadingState, EmptyState, ErrorState } from "@/components/PageStates"; import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Textarea } from "@/components/ui/textarea"; import { Label } from "@/components/ui/label"; import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"; import Link from "next/link"; import { useState } from "react";
export default function CareerAI(){const convs=useQuery({queryKey:["career-convs"],queryFn:api.careerConversations});const [out,setOut]=useState("");const [chatIn,setChatIn]=useState("");const [busy,setBusy]=useState("");
 async function run(tool:string,body:Record<string,unknown>={}){setBusy(tool);setOut("");try{const d=await api.careerAi(tool,body);setOut(JSON.stringify(d,null,2));}catch(e){setOut(e instanceof Error?e.message:"Failed");}setBusy("");}
 const tools:[string,string][]=[["analyze","Analyze my profile"],["skill-gap","Skill-gap analysis"],["suggest-projects","Suggest projects"],["review-resume","Review resume"],["review-portfolio","Review portfolio"],["action-plan","30/60/90 action plan"]];
 return <div><h1 className="font-display text-2xl font-semibold tracking-tight">Career AI</h1><p className="mt-1 text-sm text-zinc-500">Distinct tools, not a generic chat box. Each runs against your real career data.</p>
 <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{tools.map(([t,l])=><Button key={t} variant="outline" className="h-auto justify-start py-4" onClick={()=>run(t)} disabled={busy===t}>{busy===t?"Running…":l}</Button>)}</div>
 <Card className="mt-8"><CardHeader><CardTitle>Career conversation</CardTitle></CardHeader><CardContent><div className="flex gap-2"><Input value={chatIn} onChange={e=>setChatIn(e.target.value)} placeholder="Ask about roles, skills, next steps…" aria-label="Career question"/><Button onClick={()=>run("chat",{message:chatIn})} disabled={!chatIn||busy==="chat"}>Send</Button></div>
 {convs.data&&convs.data.length>0&&<div className="mt-4"><p className="text-xs text-zinc-500">Past conversations: {convs.data.length}</p></div>}
 {out&&<pre className="mt-4 max-h-[420px] overflow-auto rounded-md bg-zinc-950 p-4 text-xs text-zinc-950 whitespace-pre-wrap">{out}</pre>}</CardContent></Card></div>;}
