"use client"; import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query"; import { api } from "@/lib/api/services"; import { LoadingState, EmptyState, ErrorState } from "@/components/PageStates"; import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Textarea } from "@/components/ui/textarea"; import { Label } from "@/components/ui/label"; import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"; import Link from "next/link"; import { useState } from "react";
export default function Career(){const qc=useQueryClient();const prof=useQuery({queryKey:["profile"],queryFn:api.profile});const skills=useQuery({queryKey:["skills"],queryFn:api.skills});const edu=useQuery({queryKey:["education"],queryFn:api.education});const certs=useQuery({queryKey:["certificates"],queryFn:api.certificates});
 const [sk,setSk]=useState("");const [skCat,setSkCat]=useState("");const [skProf,setSkProf]=useState("3");
 const [inst,setInst]=useState("");const [deg,setDeg]=useState("");const [fos,setFos]=useState("");const [sDate,setSDate]=useState("");const [eDate,setEDate]=useState("");
 const [cert,setCert]=useState("");const [iss,setIss]=useState("");const [iDate,setIDate]=useState("");const [xDate,setXDate]=useState("");
 const [formErr,setFormErr]=useState("");
 const errMsg=(e:unknown)=>e instanceof Error?e.message:"Something went wrong. Try again.";
 const clearAnd=(fn:()=>void)=>{setFormErr("");fn();};
 const addSkill=useMutation({mutationFn:()=>api.createSkill({name:sk,category:skCat||"general",proficiency:parseInt(skProf,10)}),onSuccess:()=>{qc.invalidateQueries({queryKey:["skills"]});setSk("");setSkCat("");setSkProf("3");setFormErr("");},onError:(e)=>setFormErr(errMsg(e))});
 const addEdu=useMutation({mutationFn:()=>api.createEducation({institution:inst,degree:deg,field_of_study:fos,start_date:sDate||undefined,end_date:eDate||undefined}),onSuccess:()=>{qc.invalidateQueries({queryKey:["education"]});setInst("");setDeg("");setFos("");setSDate("");setEDate("");setFormErr("");},onError:(e)=>setFormErr(errMsg(e))});
 const addCert=useMutation({mutationFn:()=>api.createCertificate({title:cert,issuer:iss,issue_date:iDate||undefined,expiry_date:xDate||undefined}),onSuccess:()=>{qc.invalidateQueries({queryKey:["certificates"]});setCert("");setIss("");setIDate("");setXDate("");setFormErr("");},onError:(e)=>setFormErr(errMsg(e))});
 if(prof.isLoading) return <LoadingState/>;
 const listErr=(q:{error:unknown})=>q.error?<p className="mt-3 text-sm text-rose-600" role="alert">Couldn't load — {errMsg(q.error)}</p>:null;
 return <div><h1 className="font-display text-2xl font-semibold tracking-tight">Career Hub</h1><p className="mt-1 text-sm text-zinc-500">Your structured professional record — the source for resumes and portfolios.</p>
 <div className="mt-6 grid gap-6 lg:grid-cols-2">
 <Card><CardHeader><CardTitle>Profile</CardTitle></CardHeader><CardContent>{prof.error?<p className="text-sm text-zinc-500">Profile will be created on first save in Settings.</p>:<dl className="space-y-2 text-sm"><div><dt className="text-zinc-500">Name</dt><dd>{String(prof.data?.full_name||"—")}</dd></div><div><dt className="text-zinc-500">Headline</dt><dd>{String(prof.data?.headline||"—")}</dd></div><div><dt className="text-zinc-500">Bio</dt><dd className="text-zinc-600">{String(prof.data?.bio||"—")}</dd></div></dl>}<Link href="/app/settings"><Button size="sm" variant="outline" className="mt-4">Edit in Settings</Button></Link></CardContent></Card>
 <Card><CardHeader><CardTitle>Skills</CardTitle></CardHeader><CardContent><form onSubmit={e=>{e.preventDefault();clearAnd(()=>addSkill.mutate());}} className="space-y-2"><div className="flex gap-2"><Input value={sk} onChange={e=>setSk(e.target.value)} placeholder="Skill name" required aria-label="Skill name"/><Input value={skCat} onChange={e=>setSkCat(e.target.value)} placeholder="Category" aria-label="Category" className="max-w-[130px]"/><select value={skProf} onChange={e=>setSkProf(e.target.value)} className="h-9 rounded-lg border border-zinc-900/15 bg-white px-2 text-sm text-zinc-950 shadow-sm" aria-label="Proficiency (1-5)"><option value="1">1/5</option><option value="2">2/5</option><option value="3">3/5</option><option value="4">4/5</option><option value="5">5/5</option></select></div><Button type="submit" size="sm" disabled={addSkill.isPending}>{addSkill.isPending?"Adding…":"Add skill"}</Button></form>{formErr&&<p className="mt-2 text-sm text-rose-600" role="alert">{formErr}</p>}{listErr(skills)}{!skills.error&&(!skills.data?.length?<p className="mt-3 text-sm text-zinc-500">No skills yet.</p>:<ul className="mt-3 flex flex-wrap gap-2">{skills.data.map(s=><li key={s.id} className="rounded-full border border-zinc-900/10 bg-zinc-100 px-3 py-1 text-xs text-zinc-700">{s.name}{s.category&&s.category!=="general"?` · ${s.category}`:""}</li>)}</ul>)}</CardContent></Card>
 <Card><CardHeader><CardTitle>Education</CardTitle></CardHeader><CardContent><form onSubmit={e=>{e.preventDefault();clearAnd(()=>addEdu.mutate());}} className="space-y-2"><Input value={inst} onChange={e=>setInst(e.target.value)} placeholder="Institution" required aria-label="Institution"/><Input value={deg} onChange={e=>setDeg(e.target.value)} placeholder="Degree" required aria-label="Degree"/><Input value={fos} onChange={e=>setFos(e.target.value)} placeholder="Field of study" required aria-label="Field of study"/><div className="flex gap-2"><div className="flex-1 space-y-1"><Label>Start date</Label><Input type="date" value={sDate} onChange={e=>setSDate(e.target.value)} required aria-label="Start date"/></div><div className="flex-1 space-y-1"><Label>End date (optional)</Label><Input type="date" value={eDate} onChange={e=>setEDate(e.target.value)} aria-label="End date"/></div></div><Button type="submit" size="sm" disabled={addEdu.isPending}>{addEdu.isPending?"Adding…":"Add education"}</Button></form>{formErr&&<p className="mt-2 text-sm text-rose-600" role="alert">{formErr}</p>}{listErr(edu)}{!edu.error&&(!edu.data?.length?<p className="mt-3 text-sm text-zinc-500">No education entries.</p>:<ul className="mt-3 space-y-2">{edu.data.map(x=><li key={x.id} className="text-sm"><span className="font-medium">{x.institution||x.school}</span> — {x.degree}{x.field_of_study?` in ${x.field_of_study}`:""}</li>)}</ul>)}</CardContent></Card>
 <Card><CardHeader><CardTitle>Certificates</CardTitle></CardHeader><CardContent><form onSubmit={e=>{e.preventDefault();clearAnd(()=>addCert.mutate());}} className="space-y-2"><Input value={cert} onChange={e=>setCert(e.target.value)} placeholder="Certificate name" required aria-label="Certificate"/><Input value={iss} onChange={e=>setIss(e.target.value)} placeholder="Issuer" required aria-label="Issuer"/><div className="flex gap-2"><div className="flex-1 space-y-1"><Label>Issue date</Label><Input type="date" value={iDate} onChange={e=>setIDate(e.target.value)} required aria-label="Issue date"/></div><div className="flex-1 space-y-1"><Label>Expiry (optional)</Label><Input type="date" value={xDate} onChange={e=>setXDate(e.target.value)} aria-label="Expiry date"/></div></div><Button type="submit" size="sm" disabled={addCert.isPending}>{addCert.isPending?"Adding…":"Add certificate"}</Button></form>{formErr&&<p className="mt-2 text-sm text-rose-600" role="alert">{formErr}</p>}{listErr(certs)}{!certs.error&&(!certs.data?.length?<p className="mt-3 text-sm text-zinc-500">No certificates.</p>:<ul className="mt-3 space-y-2">{certs.data.map(c=><li key={c.id} className="text-sm"><span className="font-medium">{c.title||c.name}</span> — {c.issuer}</li>)}</ul>)}</CardContent></Card>
 </div></div>;}
