"use client"; import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query"; import { api } from "@/lib/api/services"; import { LoadingState, EmptyState, ErrorState } from "@/components/PageStates"; import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Textarea } from "@/components/ui/textarea"; import { Label } from "@/components/ui/label"; import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"; import Link from "next/link"; import { useState } from "react";
export default function Career(){const qc=useQueryClient();const prof=useQuery({queryKey:["profile"],queryFn:api.profile});const skills=useQuery({queryKey:["skills"],queryFn:api.skills});const edu=useQuery({queryKey:["education"],queryFn:api.education});const certs=useQuery({queryKey:["certificates"],queryFn:api.certificates});
 const [sk,setSk]=useState("");const [inst,setInst]=useState("");const [deg,setDeg]=useState("");const [cert,setCert]=useState("");const [iss,setIss]=useState("");const [formErr,setFormErr]=useState("");
 const errMsg=(e:unknown)=>e instanceof Error?e.message:"Something went wrong. Try again.";
 const addSkill=useMutation({mutationFn:()=>api.createSkill({name:sk}),onSuccess:()=>{qc.invalidateQueries({queryKey:["skills"]});setSk("");setFormErr("");},onError:(e)=>setFormErr(errMsg(e))});
 const addEdu=useMutation({mutationFn:()=>api.createEducation({institution:inst,degree:deg}),onSuccess:()=>{qc.invalidateQueries({queryKey:["education"]});setInst("");setDeg("");setFormErr("");},onError:(e)=>setFormErr(errMsg(e))});
 const addCert=useMutation({mutationFn:()=>api.createCertificate({title:cert,issuer:iss}),onSuccess:()=>{qc.invalidateQueries({queryKey:["certificates"]});setCert("");setIss("");setFormErr("");},onError:(e)=>setFormErr(errMsg(e))});
 if(prof.isLoading) return <LoadingState/>;
 return <div><h1 className="font-display text-2xl font-semibold tracking-tight">Career Hub</h1><p className="mt-1 text-sm text-zinc-500">Your structured professional record — the source for resumes and portfolios.</p>
 <div className="mt-6 grid gap-6 lg:grid-cols-2">
 <Card><CardHeader><CardTitle>Profile</CardTitle></CardHeader><CardContent>{prof.error?<p className="text-sm text-zinc-500">Profile will be created on first save in Settings.</p>:<dl className="space-y-2 text-sm"><div><dt className="text-zinc-500">Name</dt><dd>{String(prof.data?.full_name||"—")}</dd></div><div><dt className="text-zinc-500">Headline</dt><dd>{String(prof.data?.headline||"—")}</dd></div><div><dt className="text-zinc-500">Bio</dt><dd className="text-zinc-600">{String(prof.data?.bio||"—")}</dd></div></dl>}<Link href="/app/settings"><Button size="sm" variant="outline" className="mt-4">Edit in Settings</Button></Link></CardContent></Card>
 <Card><CardHeader><CardTitle>Skills</CardTitle></CardHeader><CardContent><form onSubmit={e=>{e.preventDefault();setFormErr("");addSkill.mutate();}} className="flex gap-2"><Input value={sk} onChange={e=>setSk(e.target.value)} placeholder="Add a skill" aria-label="Skill name"/><Button type="submit" size="sm" disabled={addSkill.isPending}>{addSkill.isPending?"Adding…":"Add"}</Button></form>{formErr&&<p className="mt-2 text-sm text-rose-600" role="alert">{formErr}</p>}{!skills.data?.length?<p className="mt-3 text-sm text-zinc-500">No skills yet.</p>:<ul className="mt-3 flex flex-wrap gap-2">{skills.data.map(s=><li key={s.id} className="rounded-full border border-zinc-900/10 bg-zinc-100 px-3 py-1 text-xs text-zinc-700">{s.name}</li>)}</ul>}</CardContent></Card>
 <Card><CardHeader><CardTitle>Education</CardTitle></CardHeader><CardContent><form onSubmit={e=>{e.preventDefault();setFormErr("");addEdu.mutate();}} className="space-y-2"><Input value={inst} onChange={e=>setInst(e.target.value)} placeholder="Institution" aria-label="Institution"/><Input value={deg} onChange={e=>setDeg(e.target.value)} placeholder="Degree" aria-label="Degree"/><Button type="submit" size="sm" disabled={addEdu.isPending}>{addEdu.isPending?"Adding…":"Add education"}</Button></form>{formErr&&<p className="mt-2 text-sm text-rose-600" role="alert">{formErr}</p>}{!edu.data?.length?<p className="mt-3 text-sm text-zinc-500">No education entries.</p>:<ul className="mt-3 space-y-2">{edu.data.map(e=><li key={e.id} className="text-sm"><span className="font-medium">{e.institution||e.school}</span> — {e.degree}</li>)}</ul>}</CardContent></Card>
 <Card><CardHeader><CardTitle>Certificates</CardTitle></CardHeader><CardContent><form onSubmit={e=>{e.preventDefault();setFormErr("");addCert.mutate();}} className="space-y-2"><Input value={cert} onChange={e=>setCert(e.target.value)} placeholder="Certificate name" aria-label="Certificate"/><Input value={iss} onChange={e=>setIss(e.target.value)} placeholder="Issuer" aria-label="Issuer"/><Button type="submit" size="sm" disabled={addCert.isPending}>{addCert.isPending?"Adding…":"Add certificate"}</Button></form>{formErr&&<p className="mt-2 text-sm text-rose-600" role="alert">{formErr}</p>}{!certs.data?.length?<p className="mt-3 text-sm text-zinc-500">No certificates.</p>:<ul className="mt-3 space-y-2">{certs.data.map(c=><li key={c.id} className="text-sm"><span className="font-medium">{c.title||c.name}</span> — {c.issuer}</li>)}</ul>}</CardContent></Card>
 </div></div>;}
