"use client"; import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query"; import { api } from "@/lib/api/services"; import { LoadingState, EmptyState, ErrorState } from "@/components/PageStates"; import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Textarea } from "@/components/ui/textarea"; import { Label } from "@/components/ui/label"; import { Badge } from "@/components/ui/badge"; import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"; import { formatDate } from "@/lib/utils"; import Link from "next/link"; import { useState } from "react";
export default function Projects(){const qc=useQueryClient();const q=useQuery({queryKey:["projects"],queryFn:api.projects});const [title,setTitle]=useState("");const [desc,setDesc]=useState("");const [search,setSearch]=useState("");
 const create=useMutation({mutationFn:()=>api.createProject({title,description:desc}),onSuccess:()=>{qc.invalidateQueries({queryKey:["projects"]});setTitle("");setDesc("");}});
 if(q.isLoading) return <LoadingState/>; if(q.error) return <ErrorState message="Failed to load projects" onRetry={()=>q.refetch()}/>;
 const list=(q.data||[]).filter(p=>((p.title||p.name||"") as string).toLowerCase().includes(search.toLowerCase()));
 return <div><h1 className="text-2xl font-semibold tracking-tight">Projects</h1><p className="mt-1 text-sm text-zinc-400">Proof-of-work that feeds your resume and portfolio.</p>
 <form onSubmit={e=>{e.preventDefault();create.mutate();}} className="mt-6 grid gap-3 rounded-lg border border-white/[0.08] bg-[#0F1511] p-4 sm:grid-cols-[1fr_1fr_auto]"><Input placeholder="Project title" value={title} onChange={e=>setTitle(e.target.value)} required aria-label="Project title"/><Input placeholder="Short description" value={desc} onChange={e=>setDesc(e.target.value)} aria-label="Description"/><Button type="submit" disabled={create.isPending}>Add project</Button></form>
 <Input className="mt-5 max-w-sm" placeholder="Search projects…" value={search} onChange={e=>setSearch(e.target.value)}/>
 {!list.length?<div className="mt-5"><EmptyState title="No projects yet" desc="Create one manually or generate from research in a workspace."/></div>:<div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{list.map(p=><Card key={p.id}><CardHeader><CardTitle>{String(p.title||p.name||"Untitled")}</CardTitle></CardHeader><CardContent><p className="line-clamp-3 text-sm text-zinc-400">{String(p.description||"No description")}</p><Link href={`/app/projects/${p.id}`} className="mt-4 inline-block text-sm font-medium text-indigo-300">Open project</Link></CardContent></Card>)}</div>}</div>;}
