"use client"; import { useParams } from "next/navigation"; import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query"; import { api } from "@/lib/api/services"; import { LoadingState, EmptyState, ErrorState } from "@/components/PageStates"; import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Textarea } from "@/components/ui/textarea"; import { Label } from "@/components/ui/label"; import { Badge } from "@/components/ui/badge"; import { useState, useRef } from "react";
import { ResearchToolOutput } from "@/components/ResearchToolOutput";
import { ModelSelector } from "@/components/ai/ModelSelector";
import { useAiModel } from "@/components/ai/useAiModel";
import { FallbackNotice } from "@/components/ai/FallbackNotice";
import type { AiModelChoice } from "@/components/ai/models";
export default function WorkspaceDetail(){const {id}=useParams<{id:string}>();const qc=useQueryClient();const ws=useQuery({queryKey:["workspace",id],queryFn:()=>api.workspace(id)});const docs=useQuery({queryKey:["ws-docs",id],queryFn:()=>api.wsDocuments(id)});const convs=useQuery({queryKey:["convs",id],queryFn:()=>api.conversations(id)});
 const [question,setQuestion]=useState("");const [answer,setAnswer]=useState("");const [citations,setCitations]=useState<{page_number?:number;source_label?:string}[]>([]);const [toolOut,setToolOut]=useState("");const [toolData,setToolData]=useState<Record<string,any>|null>(null);const [aiModel,setAiModel]=useAiModel();const [fallback,setFallback]=useState<{requested:AiModelChoice;providerUsed?:string}|null>(null);const fileRef=useRef<HTMLInputElement>(null);
 const upload=useMutation({mutationFn:(f:File)=>api.uploadDocument(id,f),onSuccess:(d)=>{qc.invalidateQueries({queryKey:["ws-docs",id]});const did=(d as {id?:string})?.id;if(did) indexM.mutate(did);}});
 const indexM=useMutation({mutationFn:(did:string)=>api.docIndex(id,did),onSuccess:()=>qc.invalidateQueries({queryKey:["ws-docs",id]})});
 const chatM=useMutation({mutationFn:()=>api.chat(id,{message: question,model: aiModel}),onSuccess:(d)=>{setAnswer((d.answer||d.response||"") as string);setCitations((d.citations||[]) as {page_number?:number;source_label?:string}[]);const r=d as Record<string,unknown>;setFallback(r.fallback_used?{requested:aiModel,providerUsed:r.provider_used as string|undefined}:null);qc.invalidateQueries({queryKey:["convs",id]});}});
 const toolM=useMutation({mutationFn:(tool:string)=>api.research(id,tool,{question:question||"Summarize the key findings",model: aiModel}),onSuccess:(d,tool)=>{setToolOut(tool as string);setToolData(d as Record<string,any>);const r=d as Record<string,unknown>;setFallback(r.fallback_used?{requested:aiModel,providerUsed:r.provider_used as string|undefined}:null);}});
 const delConv=useMutation({mutationFn:(cid:string)=>api.deleteConversation(id,cid),onSuccess:()=>qc.invalidateQueries({queryKey:["convs",id]})});
 if(ws.isLoading||docs.isLoading) return <LoadingState/>; if(ws.error) return <ErrorState message="Workspace not found or access denied" />;
 return <div><p className="text-xs text-zinc-500"><a href="/app/workspaces" className="hover:underline">Workspaces</a> / {ws.data?.name}</p><h1 className="mt-2 font-display text-2xl font-semibold tracking-tight">{ws.data?.name}</h1>{ws.data?.description&&<p className="mt-1 text-sm text-zinc-500">{ws.data.description}</p>}
 <div className="mt-8 grid gap-8 lg:grid-cols-2"><section><h2 className="text-base font-semibold">Documents</h2>
 <input ref={fileRef} type="file" accept=".pdf,.docx,.txt" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)upload.mutate(f);}}/><Button className="mt-3" size="sm" onClick={()=>fileRef.current?.click()} disabled={upload.isPending}>{upload.isPending?"Uploading…":"Upload PDF / DOCX / TXT"}</Button>
 {upload.error&&<p className="mt-2 text-sm text-rose-600">Upload failed. Check file type and size.</p>}
 <div className="mt-4">{!docs.data?.length?<EmptyState title="No documents yet" desc="Upload a paper, then index it for cited answers."/>:<ul className="divide-y divide-zinc-900/[0.06] rounded-lg border border-zinc-900/[0.08] bg-white">{docs.data.map(d=><li key={d.id} className="flex items-center justify-between gap-3 px-4 py-3"><div className="min-w-0"><p className="truncate text-sm font-medium">{d.original_filename||d.filename}</p><p className="text-xs text-zinc-500">{d.file_type} · {d.status}</p></div><Button size="sm" variant="outline" onClick={()=>indexM.mutate(d.id)} disabled={indexM.isPending}>Index</Button>{indexM.error&&<span className="max-w-xs text-xs text-rose-600">Indexing failed: {indexM.error instanceof Error ? indexM.error.message : "unknown error"} — retry.</span>}</li>)}</ul>}</div>
 <h2 className="mt-8 text-base font-semibold">Conversations</h2>{!convs.data?.length?<p className="mt-2 text-sm text-zinc-500">No conversations yet.</p>:<ul className="mt-3 space-y-2">{convs.data.map(c=><li key={c.id} className="flex items-center justify-between rounded-md border border-zinc-900/[0.08] px-3 py-2 text-sm"><span>{c.title||"Untitled"}</span><Button size="sm" variant="ghost" onClick={()=>{if(confirm("Delete this conversation?"))delConv.mutate(c.id);}}>Delete</Button></li>)}</ul>}</section>
 <section><h2 className="text-base font-semibold">Research studio</h2><div className="mt-3 space-y-3"><Label htmlFor="q">Ask your documents</Label><Textarea id="q" rows={4} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What does the literature say about…?"/><div className="flex items-center gap-2"><ModelSelector value={aiModel} onChange={setAiModel}/></div><div className="flex flex-wrap gap-2"><Button onClick={()=>chatM.mutate()} disabled={!question||chatM.isPending}>{chatM.isPending?"Thinking…":"Ask with citations"}</Button>{["summary","key-points","questions","flashcards"].map(t=><Button key={t} variant="outline" size="sm" onClick={()=>toolM.mutate(t)} disabled={toolM.isPending}>{t}</Button>)}</div>
 {fallback&&<FallbackNotice requested={fallback.requested} providerUsed={fallback.providerUsed} onDismiss={()=>setFallback(null)}/>}
 {chatM.error&&<p className="text-sm text-rose-600">{chatM.error instanceof Error ? chatM.error.message : "Couldn't answer that yet — try again."}</p>}
 {answer&&<div className="rounded-2xl border border-zinc-900/[0.08] bg-white p-4 shadow-sm"><p className="text-sm leading-relaxed whitespace-pre-wrap">{answer}</p>{citations.length>0&&<div className="mt-4 border-t border-zinc-900/[0.06] pt-3"><p className="text-xs font-medium text-zinc-500">Sources</p><ul className="mt-2 space-y-1">{citations.map((c,i)=><li key={i} className="text-xs text-zinc-500">[{i+1}] {c.source_label||"Document"}{c.page_number?` · Page ${c.page_number}`:""}</li>)}</ul></div>}</div>}
 {toolOut&&toolData&&<div className="mt-4"><ResearchToolOutput tool={toolOut} data={toolData} /></div>}
 {toolM.error&&<p className="mt-3 text-sm text-rose-600">Research failed. Try again in a moment.</p>}</div></section></div></div>;}
