"use client"; import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query"; import { api } from "@/lib/api/services"; import { LoadingState, EmptyState, ErrorState } from "@/components/PageStates"; import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Textarea } from "@/components/ui/textarea"; import { Label } from "@/components/ui/label"; import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"; import Link from "next/link"; import { useState } from "react";
import { apiUrl } from "@/lib/api/client"; import { supabase } from "@/lib/supabase";
export default function ResumePage(){const qc=useQueryClient();const q=useQuery({queryKey:["resumes"],queryFn:api.resumes});const [title,setTitle]=useState("");const [sel,setSel]=useState("");const [formErr,setFormErr]=useState("");const items=useQuery({queryKey:["resume-items",sel],queryFn:()=>api.resumeItems(sel),enabled:!!sel});
 const errMsg=(e:unknown)=>e instanceof Error?e.message:"Something went wrong. Try again.";
 const create=useMutation({mutationFn:()=>api.createResume({name:title}),onSuccess:()=>{qc.invalidateQueries({queryKey:["resumes"]});setTitle("");setFormErr("");},onError:(e)=>setFormErr(errMsg(e))});
 const [itTitle,setItTitle]=useState("");const [itSection,setItSection]=useState("project");
 const addItem=useMutation({mutationFn:()=>api.addResumeItem(sel,{section_type:itSection,title:itTitle}),onSuccess:()=>{qc.invalidateQueries({queryKey:["resume-items",sel]});setItTitle("");setFormErr("");},onError:(e)=>setFormErr(errMsg(e))});
 async function move(idx:number,dir:-1|1){if(!items.data) return; const arr=[...items.data]; const j=idx+dir; if(j<0||j>=arr.length) return; [arr[idx],arr[j]]=[arr[j],arr[idx]]; await api.reorderResumeItems(sel,arr.map((x,i)=>({id:x.id,sort_order:i}))); qc.invalidateQueries({queryKey:["resume-items",sel]});}
 async function pdf(){const {data}=await supabase.auth.getSession(); const url=apiUrl(`/api/v1/resumes/${sel}/pdf`); const r=await fetch(url,{headers:{Authorization:`Bearer ${data.session?.access_token}`}}); const b=await r.blob(); const u=URL.createObjectURL(b); window.open(u);}
 if(q.isLoading) return <LoadingState/>;
 return <div><h1 className="font-display text-2xl font-semibold tracking-tight">Resume Builder</h1><p className="mt-1 text-sm text-zinc-500">Build from verified career records. Preview mirrors the exported PDF.</p>
 <form onSubmit={e=>{e.preventDefault();setFormErr("");create.mutate();}} className="mt-6 flex max-w-lg gap-2"><Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Resume title" required aria-label="Resume title"/><Button type="submit" disabled={create.isPending}>{create.isPending?"Creating…":"New resume"}</Button></form>
 {formErr&&<p className="mt-2 text-sm text-rose-600" role="alert">{formErr}</p>}
 {!q.data?.length?<div className="mt-5"><EmptyState title="No resumes yet" desc="Create one, then attach projects, skills and education."/></div>:<div className="mt-5 grid gap-3 sm:grid-cols-3">{q.data.map(r=><button key={r.id} onClick={()=>setSel(r.id)} className={`rounded-lg border p-4 text-left ${sel===r.id?"border-indigo-500 bg-indigo-50":"border-zinc-900/[0.08] bg-white"}`}><p className="font-medium">{r.name||r.title}</p><p className="text-xs text-zinc-500">Click to edit items</p></button>)}</div>}
 {sel&&<div className="mt-8 grid gap-6 lg:grid-cols-2"><div><h2 className="font-semibold">Items</h2><form onSubmit={e=>{e.preventDefault();setFormErr("");addItem.mutate();}} className="mt-3 flex flex-wrap gap-2"><select value={itSection} onChange={e=>setItSection(e.target.value)} className="h-9 rounded-lg border border-zinc-900/15 bg-white px-2 text-sm text-zinc-950 shadow-sm" aria-label="Section"><option value="project">Project</option><option value="education">Education</option><option value="skill">Skill</option><option value="certificate">Certificate</option></select><Input value={itTitle} onChange={e=>setItTitle(e.target.value)} placeholder="Item title" required className="max-w-[220px]"/><Button type="submit" size="sm" disabled={addItem.isPending}>{addItem.isPending?"Adding…":"Add item"}</Button></form>
 {formErr&&<p className="mt-2 text-sm text-rose-600" role="alert">{formErr}</p>}
 {items.isLoading?<p className="mt-3 text-sm text-zinc-500">Loading items…</p>:!items.data?.length?<p className="mt-3 text-sm text-zinc-500">No items. Add your first above.</p>:<ul className="mt-3 space-y-2">{items.data.map((it,i)=><li key={it.id} className="flex items-center justify-between rounded-md border border-zinc-900/[0.08] px-3 py-2 text-sm"><span>{it.title} <span className="text-zinc-500">· {it.section_type}</span></span><span className="flex gap-1"><Button size="sm" variant="ghost" onClick={()=>move(i,-1)} aria-label="Move up">↑</Button><Button size="sm" variant="ghost" onClick={()=>move(i,1)} aria-label="Move down">↓</Button></span></li>)}</ul>}</div>
 <div><h2 className="font-semibold">Preview</h2><div className="mt-3 rounded-lg bg-white p-6 text-zinc-900"><p className="text-lg font-bold">{q.data?.find(r=>r.id===sel)?.name||q.data?.find(r=>r.id===sel)?.title}</p><ul className="mt-4 space-y-2 text-sm">{(items.data||[]).map(it=><li key={it.id}><span className="font-medium">{it.title}</span>{it.subtitle&&<span> — {it.subtitle}</span>}</li>)}</ul></div><Button className="mt-4" onClick={pdf}>Download PDF</Button></div></div>}</div>;}
