import { env } from "@/lib/env"; import Link from "next/link";
async function getPortfolio(slug:string){ try{ const r=await fetch(`${env.apiBase}/api/v1/public/portfolios/${slug}`,{cache:"no-store"}); if(!r.ok) return null; return r.json() as Promise<Record<string,unknown>>; }catch{ return null; } }
export default async function PublicPortfolio({params}:{params:Promise<{slug:string}>}){const {slug}=await params; const data=await getPortfolio(slug);
 if(!data) return <div className="flex min-h-screen items-center justify-center bg-white px-4 text-zinc-900"><div className="text-center"><h1 className="text-2xl font-semibold">Portfolio not found</h1><p className="mt-2 text-zinc-500">This public portfolio does not exist or is private.</p><Link href="/" className="mt-4 inline-block text-indigo-600">Go to ZEVQYN</Link></div></div>;
 const title=String(data.title||slug); const profile=(data.profile||{}) as Record<string,unknown>; const projects=(data.projects||[]) as Record<string,unknown>[]; const skills=(data.skills||[]) as Record<string,unknown>[];
 return <div className="min-h-screen bg-white text-zinc-900"><header className="border-b"><div className="mx-auto flex h-14 max-w-4xl items-center justify-between px-4"><span className="font-display font-semibold">ZEVQYN</span><span className="text-xs text-zinc-500">Public portfolio</span></div></header><main className="mx-auto max-w-4xl px-4 py-12"><p className="text-xs font-medium uppercase tracking-wider text-indigo-600">Portfolio</p><h1 className="font-display mt-3 text-4xl font-bold tracking-tight">{title}</h1>{!!profile.headline&&<p className="mt-3 text-lg text-zinc-600">{String(profile.headline)}</p>}{!!profile.bio&&<p className="mt-4 leading-relaxed text-zinc-600">{String(profile.bio)}</p>}
 {skills.length>0&&<section className="mt-10"><h2 className="text-sm font-semibold uppercase tracking-wider text-zinc-500">Skills</h2><ul className="mt-3 flex flex-wrap gap-2">{skills.map((s,i)=><li key={i} className="rounded-full bg-zinc-100 px-3 py-1 text-sm">{String(s.name||s)}</li>)}</ul></section>}
 {projects.length>0&&<section className="mt-10"><h2 className="text-sm font-semibold uppercase tracking-wider text-zinc-500">Projects</h2><div className="mt-4 space-y-4">{projects.map((p,i)=><article key={i} className="rounded-lg border p-5"><h3 className="font-semibold">{String(p.title||p.name||"Project")}</h3>{!!p.description&&<p className="mt-2 text-sm leading-relaxed text-zinc-600">{String(p.description)}</p>}</article>)}</div></section>}
 <footer className="mt-14 border-t pt-6 text-xs text-zinc-400">Built with ZEVQYN — research to career proof.</footer></main></div>;}
